import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import '../../core/config/app_config.dart';

part 'database.g.dart';

/// Routes open on the device. Stores the minimum context needed to resume.
class Routes extends Table {
  /// Route UUID. The route is in state `verificada` (the domain is
  /// `borrador | verificada`; there is no "congelada").
  TextColumn get routeId => text()();

  /// Route census code (comes from the backend frame).
  TextColumn get codigo => text().nullable()();

  /// Last time the frame (GET) was fetched to resume.
  DateTimeColumn get lastFrameSyncAt => dateTime().nullable()();

  @override
  Set<Column<Object>> get primaryKey => {routeId};
}

/// One capture = one household. Local offline-first queue.
///
/// Invariants (enforced by the repository, not by the UI):
/// - `clientId` is the idempotency key (UUID generated by the app).
/// - `orden` is monotonic, append-only per route (1, 2, 3…). It is NEVER
///   reordered or reassigned in the MVP.
/// - No coordinates: there is no lat/lon column anywhere.
/// - `loc` and `remoteId` are assigned by the server (loc = orden × 5); they
///   are stored on sync.
class Captures extends Table {
  /// UUID generated by the app. Idempotency key with the backend.
  TextColumn get clientId => text()();

  TextColumn get routeId => text()();

  /// Walk counter (append-only).
  IntColumn get orden => integer()();

  /// placa (address on the door). Optional: it may be left blank.
  TextColumn get placa => text().nullable()();

  /// manzana_catastral (from the route design). Optional.
  TextColumn get manzanaCatastral => text().nullable()();

  /// tipo_acceso (optional): e.g. puerta_calle / area_comun / otro.
  TextColumn get tipoAcceso => text().nullable()();

  /// Free-form observacion (optional).
  TextColumn get observacion => text().nullable()();

  /// loc assigned by the server (orden × 5). Null until synced.
  IntColumn get loc => integer().nullable()();

  /// id of the remote census_code. Null until synced.
  TextColumn get remoteId => text().nullable()();

  /// pending | synced | error
  TextColumn get syncStatus =>
      text().withDefault(const Constant(AppConfig.syncPending))();

  /// Last sync error (diagnostics). Null if there is none.
  TextColumn get syncError => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {clientId};
}

@DriftDatabase(tables: [Routes, Captures])
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor])
      : super(executor ?? driftDatabase(name: AppConfig.dbName));

  @override
  int get schemaVersion => 1;

  // ---- Routes ----

  Future<void> upsertRoute(RoutesCompanion route) =>
      into(routes).insertOnConflictUpdate(route);

  Future<Route?> getRoute(String routeId) =>
      (select(routes)..where((r) => r.routeId.equals(routeId)))
          .getSingleOrNull();

  Future<List<Route>> allRoutes() =>
      (select(routes)..orderBy([(r) => OrderingTerm.desc(r.lastFrameSyncAt)]))
          .get();

  // ---- Captures ----

  /// Next append-only `orden` for the route: max(orden)+1, or 1 if empty.
  Future<int> nextOrden(String routeId) async {
    final maxExpr = captures.orden.max();
    final query = selectOnly(captures)
      ..where(captures.routeId.equals(routeId))
      ..addColumns([maxExpr]);
    final row = await query.getSingle();
    final currentMax = row.read(maxExpr);
    return (currentMax ?? 0) + 1;
  }

  Stream<List<Capture>> watchCaptures(String routeId) {
    return (select(captures)
          ..where((c) => c.routeId.equals(routeId))
          ..orderBy([(c) => OrderingTerm.asc(c.orden)]))
        .watch();
  }

  Future<List<Capture>> capturesForRoute(String routeId) {
    return (select(captures)
          ..where((c) => c.routeId.equals(routeId))
          ..orderBy([(c) => OrderingTerm.asc(c.orden)]))
        .get();
  }

  Future<Capture?> getCapture(String clientId) =>
      (select(captures)..where((c) => c.clientId.equals(clientId)))
          .getSingleOrNull();

  Future<List<Capture>> pendingCaptures(String routeId) {
    return (select(captures)
          ..where((c) =>
              c.routeId.equals(routeId) &
              c.syncStatus.equals(AppConfig.syncSynced).not())
          ..orderBy([(c) => OrderingTerm.asc(c.orden)]))
        .get();
  }

  Future<void> insertCapture(CapturesCompanion capture) =>
      into(captures).insert(capture);

  Future<void> upsertCapture(CapturesCompanion capture) =>
      into(captures).insertOnConflictUpdate(capture);

  Future<bool> updateCaptureRow(String clientId, CapturesCompanion patch) {
    return (update(captures)..where((c) => c.clientId.equals(clientId)))
        .write(patch)
        .then((rows) => rows > 0);
  }
}
