import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import '../../core/config/app_config.dart';

part 'database.g.dart';

/// Routes open on the device. Stores the minimum context needed to resume.
class Routes extends Table {
  /// Route UUID. The route is in state `verificada` (the domain is
  /// `borrador | verificada`; there is no "congelada").
  TextColumn get routeId => text()();

  /// Route census code (comes from the backend frame).
  TextColumn get codigo => text().nullable()();

  /// Last time the frame (GET) was fetched to resume.
  DateTimeColumn get lastFrameSyncAt => dateTime().nullable()();

  /// Last manual send attempt for this route (Spec 4, BR7): when it happened
  /// and how it ended (an AppConfig.push* code the UI translates). Null until
  /// the first attempt. Recorded on failures too — that is the whole point:
  /// a worker who missed the message can still tell the queue was tried.
  DateTimeColumn get lastPushAt => dateTime().nullable()();
  TextColumn get lastPushOutcome => text().nullable()();

  /// Route-state locks (Spec 9), persisted so the gates work offline with the
  /// last-known value. Defaults are the fail-open (placa) / fail-closed
  /// (survey) safe states for a route created before any frame carried them.
  TextColumn get placasEstado =>
      text().withDefault(const Constant(AppConfig.placasAbierta))();
  TextColumn get surveyEstado =>
      text().withDefault(const Constant(AppConfig.surveyBloqueada))();

  /// Parada photo policy (Spec 10): when true, a face cannot close until every
  /// placa on it has a photo. Persisted from the frame / assigned routes.
  BoolColumn get fotoObligatoria =>
      boolean().withDefault(const Constant(false))();

  @override
  Set<Column<Object>> get primaryKey => {routeId};
}

/// One capture = one household. Local offline-first queue.
///
/// Invariants (enforced by the repository, not by the UI):
/// - `clientId` is the idempotency key (UUID generated by the app).
/// - `posicion` is monotonic, append-only per route (1, 2, 3…). It is NEVER
///   reordered or reassigned in the MVP.
/// - No coordinates: there is no lat/lon column anywhere.
/// - `loc` and `remoteId` are assigned by the server (loc = posicion × 5); they
///   are stored on sync.
class Captures extends Table {
  /// UUID generated by the app. Idempotency key with the backend.
  TextColumn get clientId => text()();

  TextColumn get routeId => text()();

  /// Walk counter (append-only).
  /// SQL column stays 'orden': the Dart name follows the contract rename
  /// (posicion, backend edf0f4f) without forcing a schema migration for a
  /// label users never see.
  IntColumn get posicion => integer().named('orden')();

  /// placa (address on the door). Optional: it may be left blank.
  TextColumn get placa => text().nullable()();

  /// manzana_catastral (from the route design). Optional.
  TextColumn get manzanaCatastral => text().nullable()();

  /// tipo_acceso (optional): e.g. puerta_calle / area_comun / otro.
  TextColumn get tipoAcceso => text().nullable()();

  /// Free-form observacion (optional).
  TextColumn get observacion => text().nullable()();

  /// loc assigned by the server (posicion × 5). Null until synced.
  IntColumn get loc => integer().nullable()();

  /// secuencia_parada (Spec 11): the predio's position WITHIN its parada,
  /// restarting at 1 per parada. Assigned and FROZEN by the server; null until
  /// synced (the app shows a provisional local count meanwhile) or for
  /// legacy/no-stop_id rows. Pure display — the app NEVER sends it.
  IntColumn get secuenciaParada => integer().nullable()();

  /// es_lote (Spec 12): the predio is a vacant lot ("Sin construir"). Default
  /// false; full-replacement — sent on EVERY push and re-carried from the frame
  /// (like npn). A plate-less lot (es_lote && placa null) is exempt from the
  /// mandatory photo.
  BoolColumn get esLote => boolean().withDefault(const Constant(false))();

  /// Pending relocation: the loc of the unit this one goes after (0 = start
  /// of route). Null = no mark. The contract is full-replacement, so this
  /// must ride on every push of the row or the backend clears it (Spec 2.1).
  IntColumn get insAfter => integer().nullable()();

  /// id of the remote census_code. Null until synced.
  TextColumn get remoteId => text().nullable()();

  /// NPN linked at the door (Spec 7). Rides on EVERY push of the row —
  /// full-replacement contract: omitting it clears the link server-side,
  /// exactly like ins_after. The worker never sees this value.
  TextColumn get npn => text().nullable()();

  /// Spec 15 (v4): the linked PLACA's direccion_norm, sent when a multi-unit
  /// placa is captured (npn is null then — the units are linked later, in the
  /// survey phase). Rides on EVERY push like npn (full-replacement). Null for a
  /// single-unit link (npn carries it) or a finding.
  TextColumn get direccionNorm => text().nullable()();

  /// Server-side provenance of the link (field_confirmed | manual | ...),
  /// read from the frame. Informational; never sent on push — EXCEPT that
  /// 'field_sin_match' is how a sin_r1 finding comes back (see below).
  TextColumn get npnMatchMethod => text().nullable()();

  /// CL-R7, TRI-STATE — the app mirrors the contract exactly (backend
  /// 287cf2a): true asserts the finding, false RETRACTS it, and null says
  /// nothing (the server preserves whatever it holds). It is the only
  /// field exempt from full-replacement, because an evaporated
  /// field_sin_match degrades a human finding in silence, while an
  /// evaporated npn comes back as pending and the office sees it.
  ///
  /// null after a merge = "in sync, nothing to declare"; only a deliberate
  /// local act writes true or false. Modelling it as a plain bool would
  /// force a choice between breaking retraction (omit-always) and wiping
  /// another device's finding (send-always).
  BoolColumn get sinR1 => boolean().nullable()();

  /// Parada binding (Spec 10). Rides on EVERY push like npn (full-replacement,
  /// omit → keep). Null = unassisted capture. The worker never types it — it
  /// comes from the parada.
  ///
  /// [stopId] is the correct binding from Decisions v2 (§6) on — it exists
  /// for BOTH urban and rural paradas, unlike [blockFaceId] which a rural
  /// parada has none of. [blockFaceId] keeps riding too, for compatibility.
  TextColumn get stopId => text().nullable()();
  TextColumn get blockFaceId => text().nullable()();

  /// Person who owns this row's UNSENT content (normalized login email,
  /// CL4). Null = unowned: legacy rows and the CL1 paste flow, visible to
  /// any session. Ownership only gates queue rows — synced rows are the
  /// route's shared truth and are always visible.
  TextColumn get ownerEmail => text().nullable()();

  /// pending | synced | error
  TextColumn get syncStatus =>
      text().withDefault(const Constant(AppConfig.syncPending))();

  /// Last sync error (diagnostics). Null if there is none.
  TextColumn get syncError => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {clientId};
}

/// Spec 14 — "No encontrado en campo". A NEGATIVE capture record: an R1 placa
/// the prediction pointed at that has no physical correspondence in the field
/// (no predio, no lot, no gap in the face sequence). It creates NO census_code
/// and consumes NO posicion/loc — which is why it is a **sibling** of [Captures]
/// rather than a flagged row: [Captures] keeps its hard, non-null append-only
/// `posicion`, and this mirrors the backend's own `no_encontrados` table.
/// Pushed in the SAME /field/capture/placas batch (the item carries
/// `no_encontrado: true`).
class NoEncontrados extends Table {
  /// UUID generated by the app. Idempotency key with the backend.
  TextColumn get clientId => text()();

  TextColumn get routeId => text()();

  /// The predicted R1 placa declared absent (its server-normalized address).
  /// Always structured — a not-found only exists for a concrete prediction.
  TextColumn get direccionNorm => text()();

  /// NPN of the declared placa when single-unit; null for a multi-unit placa.
  TextColumn get npn => text().nullable()();

  /// manzana_catastral the placa belongs to (from the parada).
  TextColumn get manzana => text().nullable()();

  /// Parada binding (stop_id), like a capture. Null = unassisted (not expected
  /// here — a not-found needs an assisted parada with a prediction).
  TextColumn get stopId => text().nullable()();

  /// Free-form observación (optional) — e.g. "demolido, hoy parqueadero".
  /// Persisted and sent; the backend keeps it on `no_encontrados.observacion`.
  TextColumn get observacion => text().nullable()();

  /// CL4 ownership of this UNSENT row (normalized login email). Null = unowned.
  TextColumn get ownerEmail => text().nullable()();

  /// pending | synced | error — the same queue semantics as a capture.
  TextColumn get syncStatus =>
      text().withDefault(const Constant(AppConfig.syncPending))();

  TextColumn get syncError => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {clientId};
}

/// Local copy of the tenant's addressed R1 slice (Spec 7, T7.1). Replaced
/// wholesale per tenant on refresh (full snapshot, CL-R4). The typeahead
/// reads it; capture NEVER blocks on it being stale or empty.
/// Spec 15 (v4): one row per **placa** (collapsed by manzana + direccion_norm),
/// not per unit. A per-tenant cache, fully replaced on each refresh.
class R1Directory extends Table {
  /// Tenant the row belongs to: directories of different ESPs coexist
  /// without mixing (Spec 6 isolation applies here too).
  IntColumn get tenantId => integer()();

  /// Representative NPN — the single unit's when [unidades] == 1; NULL for a
  /// multi-unit placa (captured at the placa level, by [direccionNorm]).
  TextColumn get npn => text().nullable()();

  /// Server-normalized address (the pinned algorithm) — what the typeahead
  /// matches against and what the worker sees.
  TextColumn get direccionNorm => text()();

  TextColumn get manzana => text().nullable()();

  /// Census units sharing this placa (1 normal door; >1 PH). Spec 15.
  IntColumn get unidades => integer().withDefault(const Constant(1))();

  /// Derived `unidades > 1` — display/debug only.
  BoolColumn get esConjunto => boolean().withDefault(const Constant(false))();

  /// The placa is already captured on a route — HIDE it from the typeahead
  /// (Spec 15, BR-V3). Replaces v3's per-npn `enlazadoLoc`.
  BoolColumn get capturada => boolean().withDefault(const Constant(false))();

  /// Server-parsed address components (Spec 10). The face prediction groups
  /// by these authoritative values instead of re-parsing direccionNorm, so
  /// vías with letters/suffixes ("10AS") are used as sent — never synthesised.
  /// [parseOk] false ⇒ the components are unreliable and the row is skipped
  /// for prediction.
  TextColumn get tipoVia => text().nullable()();
  TextColumn get numVia => text().nullable()();
  TextColumn get numCruce => text().nullable()();
  TextColumn get placa => text().nullable()();
  BoolColumn get parseOk => boolean().withDefault(const Constant(false))();

  /// Best-effort geographic reference (Spec 10, PC.6): corregimiento/vereda
  /// name scraped from the raw address ("SALTO DE BORDONES"), null on clean
  /// urban rows. Free text, shown only as an approximate hint.
  TextColumn get refGeografica => text().nullable()();

  // No explicit primary key: the directory is a disposable per-tenant cache,
  // fully replaced on refresh (replaceR1Slice deletes + re-inserts) and v4
  // already sends one item per placa — drift's implicit rowid suffices.
}

/// Photo evidence queue (Spec 7, T7.4). One photo per unit (the contract's
/// proposito is fixed to 'placa'); re-capturing replaces. Rows leave the
/// queue only after the server confirmed reception (2xx) — then the local
/// file is purged too. CL4 ownership applies: unsent photos belong to the
/// person who captured them.
class Evidence extends Table {
  /// The unit's capture key — sent as the upload's idempotency key together
  /// with [proposito].
  TextColumn get clientId => text()();

  TextColumn get routeId => text()();

  /// Purpose (backend TJ.3): 'placa' (Spec 7) or 'totalizador' (Spec 8,
  /// CL-E4). Both coexist for one unit, which is why it is part of the key.
  TextColumn get proposito =>
      text().withDefault(const Constant(AppConfig.propositoPlaca))();

  /// Local JPEG path (already compressed to fit the 500KB cap).
  TextColumn get filePath => text()();

  /// AppConfig.soporteDivergencia | soporteRutina (CL-R3 triggers).
  TextColumn get soporte => text()();

  TextColumn get ownerEmail => text().nullable()();

  /// pending | error (sent rows are purged, never kept).
  TextColumn get syncStatus =>
      text().withDefault(const Constant(AppConfig.syncPending))();

  TextColumn get syncError => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  /// Keyed by (unit, purpose): the placa photo and the totalizador photo of
  /// the same unit are distinct rows (backend idempotency is per this pair).
  @override
  Set<Column<Object>> get primaryKey => {clientId, proposito};
}

/// A predio's extended survey (Spec 8, T8.5). One row per anchor unit (the
/// captured placa's client_id); it holds the declared structure as a
/// document plus the STABLE /sync/push identities, so a half-done survey
/// survives closing the app (CL-E6) and re-sends are idempotent. CL4
/// ownership applies: an unsent survey belongs to the person who ran it.
class Surveys extends Table {
  /// The anchor unit's capture key — the predio this survey belongs to.
  TextColumn get anchorClientId => text()();

  TextColumn get routeId => text()();

  TextColumn get ownerEmail => text().nullable()();

  /// Stable /sync/push identities, assigned once and reused across retries
  /// (idempotency layer b): the visit and its observation_set.
  TextColumn get visitId => text()();
  TextColumn get observationSetId => text()();

  /// The declared SurveyStructure serialised (floors → units → answers +
  /// totalizador). ph/pv/instancia are DERIVED at send time, never stored.
  TextColumn get structureJson => text()();

  /// pending | synced | error — the survey leg of the Enviar chain.
  TextColumn get syncStatus =>
      text().withDefault(const Constant(AppConfig.syncPending))();

  TextColumn get syncError => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {anchorClientId};
}

/// A route's paradas (Spec 10, PC.1b) — the cache of GET .../stops, so the
/// face-by-face navigation and the sweep work offline with the last-known
/// state. The app navigates by [faceSequence]; [faceIndex] is identity/QC.
class Paradas extends Table {
  /// Unique id of the route_block_face (the parada).
  TextColumn get stopId => text()();

  TextColumn get routeId => text()();
  IntColumn get faceSequence => integer()();

  /// The route_block_face, when this parada has one. NULLABLE (Decision v2,
  /// §6): a RURAL parada — a point of the route with no manzana face — has
  /// none. The capture binds by [stopId] from here on; this rides along only
  /// for compatibility / local reference.
  TextColumn get blockFaceId => text().nullable()();

  IntColumn get faceIndex => integer().nullable()();
  TextColumn get manzana => text().nullable()();
  TextColumn get orientation => text().nullable()();

  /// The terna that fixes this face's vía + generadora (Decision v2, §7) —
  /// lives on the PARADA (not the block_face): it is what the worker visits
  /// and what the backend composes against, and a rural parada legitimately
  /// has none. All three null together = rural (§8): the worker types the
  /// predio's name (topónimo) instead of a distance.
  TextColumn get tipoVia => text().nullable()();
  TextColumn get numVia => text().nullable()();
  TextColumn get numCruce => text().nullable()();

  /// Cardinal zone suffix (NORTE/SUR/ESTE/OESTE) of the official nomenclature
  /// (address-profiles AP.1–AP.5) — from the face, never typed. Null on a
  /// face without one, or on a rural parada.
  TextColumn get cardinal => text().nullable()();

  /// Where [cardinal] sits in the composed address: 'via' (after num_via,
  /// before the '#') or 'placa' (after the distance, at the very end).
  /// Meaningless when [cardinal] is null.
  TextColumn get cardinalPosicion => text().nullable()();

  /// Effective swept state (local truth). Set optimistically offline so the
  /// next parada unlocks without waiting on the server (Decision Q1).
  BoolColumn get swept => boolean().withDefault(const Constant(false))();

  /// Whether [swept] is confirmed by the server. A local mark sets it false;
  /// a refresh preserves a still-pending local sweep rather than downgrading
  /// it. The push (PC.5) flips it true.
  BoolColumn get sweptSynced => boolean().withDefault(const Constant(true))();

  /// The face's inferred sweep direction (PC.3), stored so it does not re-flip
  /// at the face end. Null until anchored.
  TextColumn get direction => text().nullable()();

  /// The server's reason when the swept push was REJECTED on its merits
  /// (barrido_fuera_de_orden / foto_obligatoria_pendiente, PC.5). [sweptSynced]
  /// stays false so the row keeps retrying on the next Enviar — same "no
  /// verdict, no stuck state" retry philosophy as captures/evidence/surveys.
  /// Cleared on a fresh local mark (a new attempt supersedes the old verdict).
  TextColumn get sweepError => text().nullable()();

  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {stopId};
}

@DriftDatabase(
    tables: [
  Routes,
  Captures,
  NoEncontrados,
  R1Directory,
  Evidence,
  Surveys,
  Paradas
])
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor])
      : super(executor ?? driftDatabase(name: AppConfig.dbName));

  @override
  int get schemaVersion => 23;

  /// v2–v4 add nullable columns (null = the correct legacy meaning);
  /// v5 creates the R1 directory table (starts empty until first refresh).
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            await m.addColumn(captures, captures.insAfter);
          }
          if (from < 3) {
            await m.addColumn(routes, routes.lastPushAt);
            await m.addColumn(routes, routes.lastPushOutcome);
          }
          if (from < 4) {
            await m.addColumn(captures, captures.ownerEmail);
          }
          if (from < 5) {
            await m.createTable(r1Directory);
          }
          if (from < 6) {
            await m.addColumn(captures, captures.npn);
            await m.addColumn(captures, captures.npnMatchMethod);
          }
          if (from < 7) {
            await m.createTable(evidence);
          }
          if (from < 8) {
            await m.addColumn(captures, captures.sinR1);
            // v4 (Spec 15) removed r1Directory.enlazadoLoc; add it via raw SQL so
            // this historical step still compiles. The v22 step drops + recreates
            // the table anyway, so this only matters for a (now-nonexistent) <8
            // install passing through.
            await m.database.customStatement(
                'ALTER TABLE r1_directory ADD COLUMN enlazado_loc TEXT;');
          }
          if (from < 9) {
            // bool NOT NULL → nullable tri-state. Existing `false` means
            // "never asserted", which under the tri-state is null.
            // TableMigration is drift's only way to change nullability
            // (SQLite cannot ALTER a column); its experimental flag is
            // accepted deliberately — the alternative is losing the
            // distinction the contract is built on.
            // ignore: experimental_member_use
            await m.alterTable(TableMigration(
              captures,
              columnTransformer: {
                captures.sinR1: const CustomExpression<bool>(
                    'CASE WHEN sin_r1 THEN 1 ELSE NULL END'),
              },
            ));
          }
          if (from < 10) {
            // Extended survey (Spec 8): resumable local survey state, one
            // row per anchor. Starts empty until the first survey is saved.
            await m.createTable(surveys);
          }
          if (from < 11) {
            // Evidence gains `proposito` and its PK becomes
            // (client_id, proposito) so a unit can hold both a placa photo
            // and a totalizador photo (Spec 8, CL-E4). Existing rows are all
            // placa. TableMigration recreates the table with the new key.
            // ignore: experimental_member_use
            await m.alterTable(TableMigration(
              evidence,
              columnTransformer: {
                evidence.proposito:
                    const Constant<String>(AppConfig.propositoPlaca),
              },
              newColumns: [evidence.proposito],
            ));
          }
          if (from < 12) {
            // Route-state locks (Spec 9). Existing routes take the safe
            // defaults (placa open, survey blocked) until a frame refreshes
            // them.
            await m.addColumn(routes, routes.placasEstado);
            await m.addColumn(routes, routes.surveyEstado);
          }
          if (from < 13) {
            // Parada-scoped capture (Spec 10): the face binding on a capture
            // and the per-route photo policy.
            await m.addColumn(captures, captures.blockFaceId);
            await m.addColumn(routes, routes.fotoObligatoria);
          }
          if (from < 14) {
            // Paradas cache (PC.1b): offline face-by-face navigation + sweep.
            await m.createTable(paradas);
          }
          if (from < 15) {
            // Server-parsed R1 address columns (Spec 10): the prediction uses
            // them verbatim instead of re-parsing direccionNorm. Null until the
            // next R1 refresh backfills them; parseOk defaults false so a stale
            // row is skipped for prediction, never mis-grouped.
            await m.addColumn(r1Directory, r1Directory.tipoVia);
            await m.addColumn(r1Directory, r1Directory.numVia);
            await m.addColumn(r1Directory, r1Directory.numCruce);
            await m.addColumn(r1Directory, r1Directory.placa);
            await m.addColumn(r1Directory, r1Directory.parseOk);
          }
          if (from < 16) {
            // Decisions v2 (2026-09-22): every point of the route is a
            // parada, and a rural one has no face — block_face_id relaxes to
            // nullable and the parada gains its own optional terna (used to
            // compose/preview the address; all-null = rural). The capture
            // binds by stop_id from here on (block_face_id keeps riding for
            // compatibility). TableMigration recreates `paradas` for the
            // nullability change; existing values carry over unchanged.
            // ignore: experimental_member_use
            await m.alterTable(TableMigration(
              paradas,
              newColumns: [paradas.tipoVia, paradas.numVia, paradas.numCruce],
            ));
            await m.addColumn(captures, captures.stopId);
          }
          if (from < 17) {
            // address-profiles AP.1–AP.5: the parada's terna gains the
            // official nomenclature's cardinal zone suffix (NORTE/SUR/ESTE/
            // OESTE) + where it sits in the composed address. Pure additions,
            // null until the next /stops refresh backfills them.
            await m.addColumn(paradas, paradas.cardinal);
            await m.addColumn(paradas, paradas.cardinalPosicion);
          }
          if (from < 18) {
            // PC.5: the sweep push's rejection reason, so a merit-rejected
            // sweep (barrido_fuera_de_orden / foto_obligatoria_pendiente)
            // surfaces to the worker instead of retrying silently forever.
            await m.addColumn(paradas, paradas.sweepError);
          }
          if (from < 19) {
            // PC.6: best-effort geographic reference on R1 rows (corregimiento/
            // vereda), null until the next R1 refresh backfills it.
            await m.addColumn(r1Directory, r1Directory.refGeografica);
          }
          if (from < 20) {
            // Spec 11: the per-parada sequence number on a capture, assigned by
            // the server. Null until the next sync/frame backfills it; the app
            // shows a provisional local count meanwhile.
            await m.addColumn(captures, captures.secuenciaParada);
          }
          if (from < 21) {
            // Spec 12: the es_lote flag on a capture (vacant lot). Existing rows
            // default false (not a lot).
            await m.addColumn(captures, captures.esLote);
          }
          if (from < 22) {
            // Spec 15 (v4): the R1 directory collapses to one row per placa
            // (units[] nested, npn nullable, + unidades/es_conjunto/capturada).
            // The directory is a disposable per-tenant cache, so drop + recreate
            // it with the new shape; refresh() re-downloads it clean (forced when
            // empty). Captures gains direccion_norm for multi-unit placa capture.
            await m.deleteTable('r1_directory');
            await m.createTable(r1Directory);
            await m.addColumn(captures, captures.direccionNorm);
          }
          if (from < 23) {
            // Spec 14 ("No encontrado en campo"): a sibling table for negative
            // records (an R1 placa absent in the field). Starts empty; captures
            // and its posicion invariant are left untouched.
            await m.createTable(noEncontrados);
          }
        },
      );

  // ---- Routes ----

  Future<void> upsertRoute(RoutesCompanion route) =>
      into(routes).insertOnConflictUpdate(route);

  Future<Route?> getRoute(String routeId) =>
      (select(routes)..where((r) => r.routeId.equals(routeId)))
          .getSingleOrNull();

  Stream<Route?> watchRoute(String routeId) =>
      (select(routes)..where((r) => r.routeId.equals(routeId)))
          .watchSingleOrNull();

  Future<List<Route>> allRoutes() =>
      (select(routes)..orderBy([(r) => OrderingTerm.desc(r.lastFrameSyncAt)]))
          .get();

  // ---- Captures ----

  /// Next append-only `posicion` for the route: max(posicion)+1, or 1 if empty.
  Future<int> nextPosicion(String routeId) async {
    final maxExpr = captures.posicion.max();
    final query = selectOnly(captures)
      ..where(captures.routeId.equals(routeId))
      ..addColumns([maxExpr]);
    final row = await query.getSingle();
    final currentMax = row.read(maxExpr);
    return (currentMax ?? 0) + 1;
  }

  /// CL4 visibility: synced rows are the route's shared truth, always
  /// shown; an UNSENT row is shown only to its owner (or to everyone when
  /// unowned — legacy rows and the paste flow). Another person's parked
  /// queue is neither listed nor pushed.
  Expression<bool> _visibleTo(Captures c, String? owner) {
    final base =
        c.syncStatus.equals(AppConfig.syncSynced) | c.ownerEmail.isNull();
    return owner == null ? base : base | c.ownerEmail.equals(owner);
  }

  Stream<List<Capture>> watchCaptures(String routeId, {String? owner}) {
    return (select(captures)
          ..where((c) => c.routeId.equals(routeId) & _visibleTo(c, owner))
          ..orderBy([(c) => OrderingTerm.asc(c.posicion)]))
        .watch();
  }

  Future<List<Capture>> capturesForRoute(String routeId, {String? owner}) {
    return (select(captures)
          ..where((c) => c.routeId.equals(routeId) & _visibleTo(c, owner))
          ..orderBy([(c) => OrderingTerm.asc(c.posicion)]))
        .get();
  }

  Future<Capture?> getCapture(String clientId) =>
      (select(captures)..where((c) => c.clientId.equals(clientId)))
          .getSingleOrNull();

  Future<List<Capture>> pendingCaptures(String routeId, {String? owner}) {
    return (select(captures)
          ..where((c) =>
              c.routeId.equals(routeId) &
              c.syncStatus.equals(AppConfig.syncSynced).not() &
              _visibleTo(c, owner))
          ..orderBy([(c) => OrderingTerm.asc(c.posicion)]))
        .get();
  }

  /// Device-wide unsent count for the logout warning ("tienes N sin
  /// enviar"). Counts this person's rows and unowned ones.
  Future<int> pendingCountForOwner(String? owner) async {
    final countExpr = captures.clientId.count();
    final query = selectOnly(captures)
      ..where(captures.syncStatus.equals(AppConfig.syncSynced).not() &
          _visibleTo(captures, owner))
      ..addColumns([countExpr]);
    final row = await query.getSingle();
    return row.read(countExpr) ?? 0;
  }

  Future<void> insertCapture(CapturesCompanion capture) =>
      into(captures).insert(capture);

  Future<void> upsertCapture(CapturesCompanion capture) =>
      into(captures).insertOnConflictUpdate(capture);

  // ---- No encontrados (Spec 14) ----

  /// CL4 visibility, same rule as captures: a synced row is shared truth; an
  /// unsent one is visible only to its owner (or to everyone when unowned).
  Expression<bool> _neVisibleTo(NoEncontrados n, String? owner) {
    final base =
        n.syncStatus.equals(AppConfig.syncSynced) | n.ownerEmail.isNull();
    return owner == null ? base : base | n.ownerEmail.equals(owner);
  }

  Stream<List<NoEncontrado>> watchNoEncontrados(String routeId,
      {String? owner}) {
    return (select(noEncontrados)
          ..where((n) => n.routeId.equals(routeId) & _neVisibleTo(n, owner))
          ..orderBy([(n) => OrderingTerm.asc(n.createdAt)]))
        .watch();
  }

  Future<List<NoEncontrado>> noEncontradosForRoute(String routeId,
      {String? owner}) {
    return (select(noEncontrados)
          ..where((n) => n.routeId.equals(routeId) & _neVisibleTo(n, owner))
          ..orderBy([(n) => OrderingTerm.asc(n.createdAt)]))
        .get();
  }

  Future<NoEncontrado?> getNoEncontrado(String clientId) =>
      (select(noEncontrados)..where((n) => n.clientId.equals(clientId)))
          .getSingleOrNull();

  Future<void> insertNoEncontrado(NoEncontradosCompanion row) =>
      into(noEncontrados).insertOnConflictUpdate(row);

  Future<int> deleteNoEncontrado(String clientId) =>
      (delete(noEncontrados)..where((n) => n.clientId.equals(clientId))).go();

  Future<bool> updateCaptureRow(String clientId, CapturesCompanion patch) {
    return (update(captures)..where((c) => c.clientId.equals(clientId)))
        .write(patch)
        .then((rows) => rows > 0);
  }

  // ---- R1 directory (Spec 7) ----

  /// Replaces the tenant's whole slice atomically (full snapshot, CL-R4).
  Future<void> replaceR1Slice(int tenantId, List<R1DirectoryCompanion> rows) {
    return transaction(() async {
      await (delete(r1Directory)..where((r) => r.tenantId.equals(tenantId)))
          .go();
      for (final row in rows) {
        await into(r1Directory).insert(row);
      }
    });
  }

  /// Typeahead lookup: prefix-match over the normalized address, capped —
  /// the panel shows a handful, never the whole directory. The repository
  /// builds [normPrefix] from the raw typed text via the pinned normalizer.
  Future<List<R1DirectoryData>> searchR1(
    int tenantId,
    String normPrefix, {
    String? manzana,
    int limit = 8,
  }) {
    return (select(r1Directory)
          ..where((r) {
            // Spec 15 (v4): hide placas already captured on a route (BR-V3).
            var cond = r.tenantId.equals(tenantId) &
                r.capturada.equals(false) &
                r.direccionNorm.like('$normPrefix%');
            // Spec 13: scope the prefix (full-address) search to the parada's
            // manzana, exactly like searchR1Part — otherwise a full address
            // ("CALLE 13 # 3A-02") matches across ALL manzanas and the worker
            // can link a row from another one.
            final mz = manzana?.trim();
            if (mz != null && mz.isNotEmpty) {
              cond = cond & r.manzana.like('%$mz');
            }
            return cond;
          })
          ..orderBy([(r) => OrderingTerm.asc(r.direccionNorm)])
          ..limit(limit))
        .get();
  }

  // ---- Evidence queue (Spec 7, T7.4) ----

  Future<void> upsertEvidence(EvidenceCompanion row) =>
      into(evidence).insertOnConflictUpdate(row);

  Future<EvidenceData?> getEvidence(
    String clientId, {
    String proposito = AppConfig.propositoPlaca,
  }) =>
      (select(evidence)
            ..where((e) =>
                e.clientId.equals(clientId) & e.proposito.equals(proposito)))
          .getSingleOrNull();

  /// Unsent photos of a route, CL4-scoped like the capture queue.
  Future<List<EvidenceData>> pendingEvidenceForRoute(
    String routeId, {
    String? owner,
  }) {
    return (select(evidence)
          ..where((e) {
            final visible = owner == null
                ? e.ownerEmail.isNull()
                : e.ownerEmail.isNull() | e.ownerEmail.equals(owner);
            return e.routeId.equals(routeId) & visible;
          })
          ..orderBy([(e) => OrderingTerm.asc(e.createdAt)]))
        .get();
  }

  /// Live count of a route's unsent photos, CL4-scoped. The send bar
  /// watches it: photos held for WiFi outlive the capture queue, and
  /// without this they would have no way to travel (found in the E2E —
  /// the bar vanished with the queue empty while a routine photo waited).
  Stream<int> watchPendingEvidenceCount(String routeId, {String? owner}) {
    final countExpr = evidence.clientId.count();
    final query = selectOnly(evidence)
      ..where(evidence.routeId.equals(routeId) &
          (owner == null
              ? evidence.ownerEmail.isNull()
              : evidence.ownerEmail.isNull() |
                  evidence.ownerEmail.equals(owner)))
      ..addColumns([countExpr]);
    return query.watchSingle().map((row) => row.read(countExpr) ?? 0);
  }

  Future<void> deleteEvidence(
    String clientId, {
    String proposito = AppConfig.propositoPlaca,
  }) =>
      (delete(evidence)
            ..where((e) =>
                e.clientId.equals(clientId) & e.proposito.equals(proposito)))
          .go();

  Future<void> markEvidenceError(
    String clientId,
    String error, {
    String proposito = AppConfig.propositoPlaca,
  }) {
    return (update(evidence)
          ..where((e) =>
              e.clientId.equals(clientId) & e.proposito.equals(proposito)))
        .write(EvidenceCompanion(
      syncStatus: const Value(AppConfig.syncError),
      syncError: Value(error),
      updatedAt: Value(DateTime.now()),
    ));
  }

  /// Whether [npn] is already linked to a unit of this route; returns that
  /// unit's posicion (CL-R3 trigger 5 — warn, never block).
  Future<int?> npnPosicionInRoute(String routeId, String npn) async {
    final row = await (select(captures)
          ..where((c) => c.routeId.equals(routeId) & c.npn.equals(npn))
          ..limit(1))
        .getSingleOrNull();
    return row?.posicion;
  }

  /// PLACA-mode lookup (CL-R1 v1.2): contains-match on the cruce-placa
  /// fragment, optionally scoped to the current manzana (suffix match:
  /// short block codes against the R1's full 17-digit ones).
  Future<List<R1DirectoryData>> searchR1Part(
    int tenantId,
    String partPattern, {
    String? manzana,
    int limit = 8,
  }) {
    return (select(r1Directory)
          ..where((r) {
            // Spec 15 (v4): hide placas already captured on a route (BR-V3).
            var cond = r.tenantId.equals(tenantId) &
                r.capturada.equals(false) &
                r.direccionNorm.contains(partPattern);
            final mz = manzana?.trim();
            if (mz != null && mz.isNotEmpty) {
              cond = cond & r.manzana.like('%$mz');
            }
            return cond;
          })
          ..orderBy([(r) => OrderingTerm.asc(r.direccionNorm)])
          ..limit(limit))
        .get();
  }

  /// CL-R6 discovery mode: how many R1 rows of this manzana are still
  /// FREE (not linked anywhere). Zero with a non-empty block means the
  /// manzana is exhausted — everything found there is new.
  Future<({int total, int free})> r1ManzanaStats(
    int tenantId,
    String manzana,
  ) async {
    final rows = await (select(r1Directory)
          ..where(
              (r) => r.tenantId.equals(tenantId) & r.manzana.like('%$manzana')))
        .get();
    return (
      total: rows.length,
      free: rows.where((r) => !r.capturada).length,
    );
  }

  /// All R1 rows of a manzana whose server parse succeeded (Spec 10) — the
  /// candidate faces the local prediction groups over. Filtered to
  /// `parse_ok`, because a row without reliable components would be
  /// mis-grouped; the manzana match is the same suffix rule as everywhere.
  Future<List<R1DirectoryData>> r1RowsForManzana(
    int tenantId,
    String manzana,
  ) {
    final mz = manzana.trim();
    return (select(r1Directory)
          ..where((r) =>
              r.tenantId.equals(tenantId) &
              r.parseOk.equals(true) &
              r.manzana.like('%$mz')))
        .get();
  }

  /// A representative geographic reference for a manzana (Spec 10, PC.6): the
  /// first non-null `ref_geografica` among the manzana's R1 rows — best-effort
  /// context for the face card. Null when none of the rows carry one.
  Future<String?> r1RefForManzana(int tenantId, String manzana) async {
    final mz = manzana.trim();
    final row = await (select(r1Directory)
          ..where((r) =>
              r.tenantId.equals(tenantId) &
              r.manzana.like('%$mz') &
              r.refGeografica.isNotNull())
          ..limit(1))
        .getSingleOrNull();
    return row?.refGeografica;
  }

  /// PC.3b (Decisions v2 §4/§7): distance-only lookup for a parada WITH a
  /// terna — the worker types only the distance, so the search narrows to the
  /// EXACT `(tipo_via, num_via, num_cruce)` of the parada's face (known
  /// upfront, not derived from an anchor) instead of a free-text fragment.
  /// [manzana] is an extra safety scope, skipped when the parada carries none.
  Future<List<R1DirectoryData>> r1SearchByDistance(
    int tenantId, {
    required String tipoVia,
    required String numVia,
    required String numCruce,
    required String distancePrefix,
    String? manzana,
    int limit = 8,
  }) {
    return (select(r1Directory)
          ..where((r) {
            // Spec 15 (v4): hide placas already captured on a route (BR-V3).
            var cond = r.tenantId.equals(tenantId) &
                r.capturada.equals(false) &
                r.parseOk.equals(true) &
                r.tipoVia.equals(tipoVia) &
                r.numVia.equals(numVia) &
                r.numCruce.equals(numCruce) &
                r.placa.like('$distancePrefix%');
            final mz = manzana?.trim();
            if (mz != null && mz.isNotEmpty) {
              cond = cond & r.manzana.like('%$mz');
            }
            return cond;
          })
          ..orderBy([(r) => OrderingTerm.asc(r.placa)])
          ..limit(limit))
        .get();
  }

  /// The directory row behind an npn, to NAME an existing link in the
  /// editor (the worker sees the address, never the npn).
  Future<R1DirectoryData?> r1ByNpn(int tenantId, String npn) =>
      (select(r1Directory)
            ..where((r) => r.tenantId.equals(tenantId) & r.npn.equals(npn)))
          .getSingleOrNull();

  /// Spec 15 (v4): the directory row for a multi-unit placa, resolved by its
  /// direccion_norm within a manzana — a multi-unit anchor has no npn.
  Future<R1DirectoryData?> r1ByDireccionNorm(
    int tenantId,
    String manzana,
    String direccionNorm,
  ) {
    final mz = manzana.trim();
    return (select(r1Directory)
          ..where((r) =>
              r.tenantId.equals(tenantId) &
              r.manzana.like('%$mz') &
              r.direccionNorm.equals(direccionNorm))
          ..limit(1))
        .getSingleOrNull();
  }

  Future<int> r1CountForTenant(int tenantId) async {
    // v4: npn is nullable (multi-unit placas have none) — count a non-null
    // column so those rows are included.
    final countExpr = r1Directory.direccionNorm.count();
    final query = selectOnly(r1Directory)
      ..where(r1Directory.tenantId.equals(tenantId))
      ..addColumns([countExpr]);
    return (await query.getSingle()).read(countExpr) ?? 0;
  }

  // ---- Surveys (Spec 8, T8.5) ----

  /// CL4 visibility, same rule as captures: a synced survey is the route's
  /// shared truth (always shown); an unsent one is shown only to its owner
  /// (or to everyone when unowned).
  Expression<bool> _surveyVisibleTo(Surveys s, String? owner) {
    final base =
        s.syncStatus.equals(AppConfig.syncSynced) | s.ownerEmail.isNull();
    return owner == null ? base : base | s.ownerEmail.equals(owner);
  }

  Future<void> upsertSurvey(SurveysCompanion survey) =>
      into(surveys).insertOnConflictUpdate(survey);

  Future<Survey?> getSurvey(String anchorClientId) =>
      (select(surveys)..where((s) => s.anchorClientId.equals(anchorClientId)))
          .getSingleOrNull();

  Stream<Survey?> watchSurvey(String anchorClientId) =>
      (select(surveys)..where((s) => s.anchorClientId.equals(anchorClientId)))
          .watchSingleOrNull();

  /// Every survey of a route the caller may see — the resume list joins this
  /// to hang a per-unit survey-state chip (CL-E1).
  Stream<List<Survey>> watchSurveysForRoute(String routeId, {String? owner}) {
    return (select(surveys)
          ..where(
              (s) => s.routeId.equals(routeId) & _surveyVisibleTo(s, owner)))
        .watch();
  }

  /// Unsent surveys of a route, CL4-scoped — the survey leg of the Enviar
  /// chain pushes these.
  Future<List<Survey>> pendingSurveys(String routeId, {String? owner}) {
    return (select(surveys)
          ..where((s) =>
              s.routeId.equals(routeId) &
              s.syncStatus.equals(AppConfig.syncSynced).not() &
              _surveyVisibleTo(s, owner))
          ..orderBy([(s) => OrderingTerm.asc(s.createdAt)]))
        .get();
  }

  /// Live count of a route's unsent surveys, CL4-scoped (for the send bar).
  Stream<int> watchPendingSurveyCount(String routeId, {String? owner}) {
    final countExpr = surveys.anchorClientId.count();
    final query = selectOnly(surveys)
      ..where(surveys.routeId.equals(routeId) &
          surveys.syncStatus.equals(AppConfig.syncSynced).not() &
          _surveyVisibleTo(surveys, owner))
      ..addColumns([countExpr]);
    return query.watchSingle().map((row) => row.read(countExpr) ?? 0);
  }

  Future<bool> updateSurveyRow(String anchorClientId, SurveysCompanion patch) {
    return (update(surveys)
          ..where((s) => s.anchorClientId.equals(anchorClientId)))
        .write(patch)
        .then((rows) => rows > 0);
  }

  Future<void> deleteSurvey(String anchorClientId) =>
      (delete(surveys)..where((s) => s.anchorClientId.equals(anchorClientId)))
          .go();

  // ---- Paradas (Spec 10, PC.1b) ----

  Stream<List<Parada>> watchStops(String routeId) => (select(paradas)
        ..where((p) => p.routeId.equals(routeId))
        ..orderBy([(p) => OrderingTerm.asc(p.faceSequence)]))
      .watch();

  Future<List<Parada>> stopsForRoute(String routeId) => (select(paradas)
        ..where((p) => p.routeId.equals(routeId))
        ..orderBy([(p) => OrderingTerm.asc(p.faceSequence)]))
      .get();

  Future<Parada?> getParada(String stopId) =>
      (select(paradas)..where((p) => p.stopId.equals(stopId)))
          .getSingleOrNull();

  Future<void> upsertParada(ParadasCompanion parada) =>
      into(paradas).insertOnConflictUpdate(parada);

  Future<void> deleteStopsForRoute(String routeId) =>
      (delete(paradas)..where((p) => p.routeId.equals(routeId))).go();

  /// Replaces a route's paradas atomically (the repository computes the merge
  /// with local state first; a re-planned route drops stops no longer sent).
  Future<void> replaceRouteStops(String routeId, List<ParadasCompanion> rows) {
    return transaction(() async {
      await (delete(paradas)..where((p) => p.routeId.equals(routeId))).go();
      for (final r in rows) {
        await into(paradas).insert(r);
      }
    });
  }

  Future<bool> updateParadaRow(String stopId, ParadasCompanion patch) =>
      (update(paradas)..where((p) => p.stopId.equals(stopId)))
          .write(patch)
          .then((rows) => rows > 0);

  /// Paradas whose local sweep has not been pushed yet (PC.5 pushes these).
  Future<List<Parada>> pendingSweeps(String routeId) => (select(paradas)
        ..where((p) => p.routeId.equals(routeId) & p.sweptSynced.equals(false)))
      .get();
}
