import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import '../../core/config/app_config.dart';

part 'database.g.dart';

/// Routes open on the device. Stores the minimum context needed to resume.
class Routes extends Table {
  /// Route UUID. The route is in state `verificada` (the domain is
  /// `borrador | verificada`; there is no "congelada").
  TextColumn get routeId => text()();

  /// Route census code (comes from the backend frame).
  TextColumn get codigo => text().nullable()();

  /// Last time the frame (GET) was fetched to resume.
  DateTimeColumn get lastFrameSyncAt => dateTime().nullable()();

  /// Last manual send attempt for this route (Spec 4, BR7): when it happened
  /// and how it ended (an AppConfig.push* code the UI translates). Null until
  /// the first attempt. Recorded on failures too — that is the whole point:
  /// a worker who missed the message can still tell the queue was tried.
  DateTimeColumn get lastPushAt => dateTime().nullable()();
  TextColumn get lastPushOutcome => text().nullable()();

  @override
  Set<Column<Object>> get primaryKey => {routeId};
}

/// One capture = one household. Local offline-first queue.
///
/// Invariants (enforced by the repository, not by the UI):
/// - `clientId` is the idempotency key (UUID generated by the app).
/// - `posicion` is monotonic, append-only per route (1, 2, 3…). It is NEVER
///   reordered or reassigned in the MVP.
/// - No coordinates: there is no lat/lon column anywhere.
/// - `loc` and `remoteId` are assigned by the server (loc = posicion × 5); they
///   are stored on sync.
class Captures extends Table {
  /// UUID generated by the app. Idempotency key with the backend.
  TextColumn get clientId => text()();

  TextColumn get routeId => text()();

  /// Walk counter (append-only).
  /// SQL column stays 'orden': the Dart name follows the contract rename
  /// (posicion, backend edf0f4f) without forcing a schema migration for a
  /// label users never see.
  IntColumn get posicion => integer().named('orden')();

  /// placa (address on the door). Optional: it may be left blank.
  TextColumn get placa => text().nullable()();

  /// manzana_catastral (from the route design). Optional.
  TextColumn get manzanaCatastral => text().nullable()();

  /// tipo_acceso (optional): e.g. puerta_calle / area_comun / otro.
  TextColumn get tipoAcceso => text().nullable()();

  /// Free-form observacion (optional).
  TextColumn get observacion => text().nullable()();

  /// loc assigned by the server (posicion × 5). Null until synced.
  IntColumn get loc => integer().nullable()();

  /// Pending relocation: the loc of the unit this one goes after (0 = start
  /// of route). Null = no mark. The contract is full-replacement, so this
  /// must ride on every push of the row or the backend clears it (Spec 2.1).
  IntColumn get insAfter => integer().nullable()();

  /// id of the remote census_code. Null until synced.
  TextColumn get remoteId => text().nullable()();

  /// NPN linked at the door (Spec 7). Rides on EVERY push of the row —
  /// full-replacement contract: omitting it clears the link server-side,
  /// exactly like ins_after. The worker never sees this value.
  TextColumn get npn => text().nullable()();

  /// Server-side provenance of the link (field_confirmed | manual | ...),
  /// read from the frame. Informational; never sent on push.
  TextColumn get npnMatchMethod => text().nullable()();

  /// Person who owns this row's UNSENT content (normalized login email,
  /// CL4). Null = unowned: legacy rows and the CL1 paste flow, visible to
  /// any session. Ownership only gates queue rows — synced rows are the
  /// route's shared truth and are always visible.
  TextColumn get ownerEmail => text().nullable()();

  /// pending | synced | error
  TextColumn get syncStatus =>
      text().withDefault(const Constant(AppConfig.syncPending))();

  /// Last sync error (diagnostics). Null if there is none.
  TextColumn get syncError => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {clientId};
}

/// Local copy of the tenant's addressed R1 slice (Spec 7, T7.1). Replaced
/// wholesale per tenant on refresh (full snapshot, CL-R4). The typeahead
/// reads it; capture NEVER blocks on it being stale or empty.
class R1Directory extends Table {
  /// Tenant the row belongs to: directories of different ESPs coexist
  /// without mixing (Spec 6 isolation applies here too).
  IntColumn get tenantId => integer()();

  TextColumn get npn => text()();

  /// Raw address as the R1 carries it.
  TextColumn get direccion => text()();

  /// Server-normalized address (the pinned algorithm) — what the typeahead
  /// matches against and what the worker sees.
  TextColumn get direccionNorm => text()();

  TextColumn get manzana => text().nullable()();

  @override
  Set<Column<Object>> get primaryKey => {tenantId, npn};
}

/// Photo evidence queue (Spec 7, T7.4). One photo per unit (the contract's
/// proposito is fixed to 'placa'); re-capturing replaces. Rows leave the
/// queue only after the server confirmed reception (2xx) — then the local
/// file is purged too. CL4 ownership applies: unsent photos belong to the
/// person who captured them.
class Evidence extends Table {
  /// The unit's capture key — also the upload's idempotency key.
  TextColumn get clientId => text()();

  TextColumn get routeId => text()();

  /// Local JPEG path (already compressed to fit the 500KB cap).
  TextColumn get filePath => text()();

  /// AppConfig.soporteDivergencia | soporteRutina (CL-R3 triggers).
  TextColumn get soporte => text()();

  TextColumn get ownerEmail => text().nullable()();

  /// pending | error (sent rows are purged, never kept).
  TextColumn get syncStatus =>
      text().withDefault(const Constant(AppConfig.syncPending))();

  TextColumn get syncError => text().nullable()();

  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column<Object>> get primaryKey => {clientId};
}

@DriftDatabase(tables: [Routes, Captures, R1Directory, Evidence])
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor])
      : super(executor ?? driftDatabase(name: AppConfig.dbName));

  @override
  int get schemaVersion => 7;

  /// v2–v4 add nullable columns (null = the correct legacy meaning);
  /// v5 creates the R1 directory table (starts empty until first refresh).
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            await m.addColumn(captures, captures.insAfter);
          }
          if (from < 3) {
            await m.addColumn(routes, routes.lastPushAt);
            await m.addColumn(routes, routes.lastPushOutcome);
          }
          if (from < 4) {
            await m.addColumn(captures, captures.ownerEmail);
          }
          if (from < 5) {
            await m.createTable(r1Directory);
          }
          if (from < 6) {
            await m.addColumn(captures, captures.npn);
            await m.addColumn(captures, captures.npnMatchMethod);
          }
          if (from < 7) {
            await m.createTable(evidence);
          }
        },
      );

  // ---- Routes ----

  Future<void> upsertRoute(RoutesCompanion route) =>
      into(routes).insertOnConflictUpdate(route);

  Future<Route?> getRoute(String routeId) =>
      (select(routes)..where((r) => r.routeId.equals(routeId)))
          .getSingleOrNull();

  Stream<Route?> watchRoute(String routeId) =>
      (select(routes)..where((r) => r.routeId.equals(routeId)))
          .watchSingleOrNull();

  Future<List<Route>> allRoutes() =>
      (select(routes)..orderBy([(r) => OrderingTerm.desc(r.lastFrameSyncAt)]))
          .get();

  // ---- Captures ----

  /// Next append-only `posicion` for the route: max(posicion)+1, or 1 if empty.
  Future<int> nextPosicion(String routeId) async {
    final maxExpr = captures.posicion.max();
    final query = selectOnly(captures)
      ..where(captures.routeId.equals(routeId))
      ..addColumns([maxExpr]);
    final row = await query.getSingle();
    final currentMax = row.read(maxExpr);
    return (currentMax ?? 0) + 1;
  }

  /// CL4 visibility: synced rows are the route's shared truth, always
  /// shown; an UNSENT row is shown only to its owner (or to everyone when
  /// unowned — legacy rows and the paste flow). Another person's parked
  /// queue is neither listed nor pushed.
  Expression<bool> _visibleTo(Captures c, String? owner) {
    final base =
        c.syncStatus.equals(AppConfig.syncSynced) | c.ownerEmail.isNull();
    return owner == null ? base : base | c.ownerEmail.equals(owner);
  }

  Stream<List<Capture>> watchCaptures(String routeId, {String? owner}) {
    return (select(captures)
          ..where((c) => c.routeId.equals(routeId) & _visibleTo(c, owner))
          ..orderBy([(c) => OrderingTerm.asc(c.posicion)]))
        .watch();
  }

  Future<List<Capture>> capturesForRoute(String routeId, {String? owner}) {
    return (select(captures)
          ..where((c) => c.routeId.equals(routeId) & _visibleTo(c, owner))
          ..orderBy([(c) => OrderingTerm.asc(c.posicion)]))
        .get();
  }

  Future<Capture?> getCapture(String clientId) =>
      (select(captures)..where((c) => c.clientId.equals(clientId)))
          .getSingleOrNull();

  Future<List<Capture>> pendingCaptures(String routeId, {String? owner}) {
    return (select(captures)
          ..where((c) =>
              c.routeId.equals(routeId) &
              c.syncStatus.equals(AppConfig.syncSynced).not() &
              _visibleTo(c, owner))
          ..orderBy([(c) => OrderingTerm.asc(c.posicion)]))
        .get();
  }

  /// Device-wide unsent count for the logout warning ("tienes N sin
  /// enviar"). Counts this person's rows and unowned ones.
  Future<int> pendingCountForOwner(String? owner) async {
    final countExpr = captures.clientId.count();
    final query = selectOnly(captures)
      ..where(captures.syncStatus.equals(AppConfig.syncSynced).not() &
          _visibleTo(captures, owner))
      ..addColumns([countExpr]);
    final row = await query.getSingle();
    return row.read(countExpr) ?? 0;
  }

  Future<void> insertCapture(CapturesCompanion capture) =>
      into(captures).insert(capture);

  Future<void> upsertCapture(CapturesCompanion capture) =>
      into(captures).insertOnConflictUpdate(capture);

  Future<bool> updateCaptureRow(String clientId, CapturesCompanion patch) {
    return (update(captures)..where((c) => c.clientId.equals(clientId)))
        .write(patch)
        .then((rows) => rows > 0);
  }

  // ---- R1 directory (Spec 7) ----

  /// Replaces the tenant's whole slice atomically (full snapshot, CL-R4).
  Future<void> replaceR1Slice(int tenantId, List<R1DirectoryCompanion> rows) {
    return transaction(() async {
      await (delete(r1Directory)..where((r) => r.tenantId.equals(tenantId)))
          .go();
      for (final row in rows) {
        await into(r1Directory).insert(row);
      }
    });
  }

  /// Typeahead lookup: prefix-match over the normalized address, capped —
  /// the panel shows a handful, never the whole directory. The repository
  /// builds [normPrefix] from the raw typed text via the pinned normalizer.
  Future<List<R1DirectoryData>> searchR1(
    int tenantId,
    String normPrefix, {
    int limit = 8,
  }) {
    return (select(r1Directory)
          ..where((r) =>
              r.tenantId.equals(tenantId) &
              r.direccionNorm.like('$normPrefix%'))
          ..orderBy([(r) => OrderingTerm.asc(r.direccionNorm)])
          ..limit(limit))
        .get();
  }

  // ---- Evidence queue (Spec 7, T7.4) ----

  Future<void> upsertEvidence(EvidenceCompanion row) =>
      into(evidence).insertOnConflictUpdate(row);

  Future<EvidenceData?> getEvidence(String clientId) =>
      (select(evidence)..where((e) => e.clientId.equals(clientId)))
          .getSingleOrNull();

  /// Unsent photos of a route, CL4-scoped like the capture queue.
  Future<List<EvidenceData>> pendingEvidenceForRoute(
    String routeId, {
    String? owner,
  }) {
    return (select(evidence)
          ..where((e) {
            final visible = owner == null
                ? e.ownerEmail.isNull()
                : e.ownerEmail.isNull() | e.ownerEmail.equals(owner);
            return e.routeId.equals(routeId) & visible;
          })
          ..orderBy([(e) => OrderingTerm.asc(e.createdAt)]))
        .get();
  }

  Future<void> deleteEvidence(String clientId) =>
      (delete(evidence)..where((e) => e.clientId.equals(clientId))).go();

  Future<void> markEvidenceError(String clientId, String error) {
    return (update(evidence)..where((e) => e.clientId.equals(clientId)))
        .write(EvidenceCompanion(
      syncStatus: const Value(AppConfig.syncError),
      syncError: Value(error),
      updatedAt: Value(DateTime.now()),
    ));
  }

  /// Whether [npn] is already linked to a unit of this route; returns that
  /// unit's posicion (CL-R3 trigger 5 — warn, never block).
  Future<int?> npnPosicionInRoute(String routeId, String npn) async {
    final row = await (select(captures)
          ..where((c) => c.routeId.equals(routeId) & c.npn.equals(npn))
          ..limit(1))
        .getSingleOrNull();
    return row?.posicion;
  }

  Future<int> r1CountForTenant(int tenantId) async {
    final countExpr = r1Directory.npn.count();
    final query = selectOnly(r1Directory)
      ..where(r1Directory.tenantId.equals(tenantId))
      ..addColumns([countExpr]);
    return (await query.getSingle()).read(countExpr) ?? 0;
  }
}
