# R8 keep rules for release builds.
#
# google_mlkit_text_recognition (the plate OCR, see lib/core/ocr/plate_ocr.dart)
# references the Chinese, Devanagari, Japanese and Korean script recognizers in
# its initialize() switch, but this app bundles only the Latin recognizer, so
# those classes are absent when R8 runs. We never invoke them -> suppress the
# missing-class warnings. Rules generated by R8 (missing_rules.txt).
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions
